name: stellarium-daily # you probably want to 'snapcraft register <name>'
base: core24
summary: Free, open source planetarium software
description: |
  Stellarium renders 3D photo-realistic skies in real-time. With Stellarium, you
  really see what you can see with your eyes, binoculars or a small telescope.
adopt-info: stellarium
donation: https://opencollective.com/stellarium/donate
issues: https://github.com/Stellarium/stellarium/issues 
website: https://stellarium.org
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
#Obsolete in Core22
#architectures: #build Architectures
#   - build-on: amd64 
#   - build-on: arm64

#Core24
platforms:
  amd64:
    build-on: amd64
    build-for: amd64
  arm64:
    build-on: arm64
    build-for: arm64
    
    
# this line enables LZO compression for the snap
compression: lzo

#links:
#website: https://stellarium.org
#issues: [https://github.com/t4saha/stellarium-snap/issues, https://github.com/Stellarium/stellarium/issues]
#contact: https://github.com/t4saha/stellarium-snap
#help: https://github.com/Stellarium/stellarium/releases/download/v0.22.2/stellarium_user_guide-0.22.2-1.pdf
#translation: https://www.transifex.com/stellarium/stellarium

apps:
  stellarium:
    command: bin/desktop-launch $SNAP/usr/bin/stellarium
    plugs: [desktop, desktop-legacy, wayland, browser-support, x11, unity7, gsettings, opengl, network, network-bind, audio-playback, home, raw-usb]
    common-id: org.stellarium.Stellarium
    #shared interfaces
    
    environment:
      HOME: "$SNAP_USER_COMMON"
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio
      QT_PLUGIN_PATH: $QT_PLUGIN_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins
      LIBGL_DRIVERS_PATH: $LIBGL_DRIVERS_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri
      #QTWEBENGINEPROCESS_PATH: $QTWEBENGINEPROCESS_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/libexec/QtWebEngineProcess:$SNAP/usr/lib/qt6/libexec/QtWebEngineProcess
      #DISABLE_WAYLAND: 1 # wayland is broken
      #QT_QPA_PLATFORMTHEME: xcb # gtk3 is very slow and buggy
      QTWEBENGINEPROCESS_PATH: $QTWEBENGINEPROCESS_PATH:$SNAP/usr/lib/qt6/libexec/QtWebEngineProcess
      QTWEBENGINE_DISABLE_SANDBOX: 1

layout:
  /usr/share/qt6:
    bind: $SNAP/usr/share/qt6
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy

parts:
  stellarium:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
    source: https://github.com/Stellarium/stellarium.git
    source-type: git
    parse-info: [usr/share/metainfo/org.stellarium.Stellarium.appdata.xml] #appstream info
    after: [desktop-stellarium]
    override-pull: |
      # Checkout that latest stable version
      last_committed_tag="$(git ls-remote --tags https://github.com/Stellarium/stellarium.git | grep -v {} | awk -F/ '{ print $3 }' | sort -V |tail -n 1)"
      last_released_tag="$(snap info stellarium-daily | awk '$1 == "latest/beta:" { print $2 }')"
      
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git clone -b "${last_committed_tag}" --depth 1 https://github.com/Stellarium/stellarium.git $CRAFT_PART_SRC
      else
        craftctl default
      fi
      # Point icon to the correct location
      sed -i.bak -e 's|Icon=stellarium|Icon=/usr/share/icons/hicolor/64x64/apps/stellarium.png|g' data/org.stellarium.Stellarium.desktop
      craftctl set version=$(git describe --tags) 
    override-build: |
      if [ "$(arch)" = "aarch64" ]; then
        cmake $CRAFT_PART_SRC -DENABLE_SHOWMYSKY=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$CRAFT_PART_INSTALL/usr
        make
        make install
      else
        craftctl default
      fi
      #find / ! -readable -prune -o -type f -name "libQt6WebEngineCore.so.*" -exec ls {} \; -exec execstack --clear-execstack {} \; || true
    build-packages:
      #Essential Build Dependencies
      - build-essential
      - zlib1g-dev
      - libgl1-mesa-dev
      - libdrm-dev
      #Optional Build Dependencies
      - gettext
      - doxygen
      - graphviz
      - libgps-dev
      - libnlopt-cxx-dev
      - libexiv2-dev
      - libtbb-dev
      #ShowMySky Build Dependencies
      - libglm-dev
      - libeigen3-dev
      #XKB Build Dependencies
      - libxkbcommon-x11-dev
      #QT6 Build Dependencies
      - qt6-base-dev
      - qt6-base-private-dev
      - qt6-multimedia-dev
      - qt6-positioning-dev
      - qt6-tools-dev
      - qt6-tools-dev-tools
      - qt6-base-dev-tools
      - qt6-qpa-plugins
      - qt6-image-formats-plugins
      - qt6-l10n-tools
      - qt6-webengine-dev
      - qt6-webengine-dev-tools
      #- libqt6charts6-dev
      - qt6-charts-dev
      #- libqt6opengl6-dev
      - libqt6positioning6-plugins
      #- libqt6serialport6-dev
      - qt6-serialport-dev
      - libfast-float-dev
      # for execstack flag removal
      - execstack
      #Obsolete Dependencies
      #- libqt6svg6-dev
      #- mesa-common-dev
      #- qt6-declarative-dev
      #- qt6-declarative-dev-tools
      #- libxcb-xkb-dev
      #- libxkbcommon-dev      
      #- linguist-qt6
      #- libqt6webchannel6-dev
      #- libqt6webenginewidgets6
      #- libqt6webengine6-data
      #- libqt6webenginecore6-bin
    stage-packages:
      #Media Runtime Dependencies
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-libav
      - gstreamer1.0-vaapi
      #QT6 Runtime Dependencies
      - libqt6multimedia6
      - libqt6multimediawidgets6
      #- libqt6opengl6
      - libqt6opengl6t64
      #- libqt6openglwidgets6
      - libqt6openglwidgets6t64
      - libqt6positioning6
      #- libqt6printsupport6
      - libqt6printsupport6t64
      - libqt6serialport6
      - libqt6charts6
      #- libqt6core6
      - libqt6core6t64
      #- libqt6dbus6
      - libqt6dbus6t64
      #- libqt6network6
      - libqt6network6t64
      #- libqt6gui6
      - libqt6gui6t64
      - libqt6qml6
      - libqt6qmlmodels6
      - libqt6quick6
      - libqt6quickwidgets6
      - libqt6webchannel6
      - libqt6webenginecore6-bin
      - libqt6webenginecore6
      - libqt6webengine6-data
      - libqt6webenginewidgets6
      #- libqt6widgets6
      - libqt6widgets6t64
      - libqt6concurrent6t64
      - qt6-gtk-platformtheme
      #- qt6-wayland #not working
      #GPS Funcionality
      #- libgps28
      - libgps30t64
      #OpenGL Runtime Dependencies
      - libglu1-mesa
      #- freeglut3
      - libglut3.12
      #Obsolete Runtime Dependencies
      #- libasyncns0
      #- libflac8
      #- gtk3-nocsd
      #- libogg0
      #- libsndfile1
      #- libvorbis0a
      #- libvorbisenc2
      #- libpulse0
      #Other Dependencies
      - libnlopt-cxx0
      - libexiv2-27
      - libnlopt0
      - libmd4c-dev
      - libmd4c-html0-dev
      - libtbb12
      
  cleanup:
    after: [desktop-stellarium, stellarium]
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core24
    override-prime: |
      set -eux
      for CRUFT in bug lintian man; do
        rm -rf $CRAFT_PRIME/usr/share/$CRUFT
      done
      for snap in "core24"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
      done
      find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $CRAFT_PRIME/usr/share -type d -empty -delete
      
  desktop-stellarium:
    source: https://github.com/t4saha/snapcraft-desktop-helpers-Qt6.git
    source-subdir: qt
    source-depth : 1
    plugin: make
    make-parameters: ["FLAVOR=qt6"]
    build-packages:
      - build-essential
      - qt6-base-dev
      - dpkg-dev
      - software-properties-common
    stage-packages:
      #Kebourd I/O
      - libxkbcommon0
      - xkb-data
      #Theming
      - fonts-ubuntu
      - dmz-cursor-theme
      - adwaita-icon-theme
      - qt6-gtk-platformtheme
      - libqt6svg6 # for loading icon themes which are svg
      #- libgtk2.0-0
      - libgtk2.0-0t64
      - shared-mime-info
      #- libgdk-pixbuf2.0-0
      #User Configaration
      - locales-all
      - xdg-user-dirs
      #QT6
      - qt6-qpa-plugins
      - qt6-wayland
      - libqt6gui6t64
      #Other
      - libgtk-3-common
      - libgtk-3-0t64
      - libglib2.0-bin
      #- libglib2.0-0
      - libnvidia-egl-wayland1
      - libglib2.0-0t64
      - libglib2.0-data
      #- libssl3t64
      - gsettings-desktop-schemas
      #- fcitx-frontend-qt6

plugs:
  # Support for common GTK themes
  # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
