name: stellarium-daily # you probably want to 'snapcraft register <name>'
#base: core18
base: core20 # the base snap is the execution environment for this snap
#version: '0.+git' # just for humans, typically '1.2+git' or '1.3.2'
#version : 0.20.1
#summary: Free, open source planetarium software # 79 char long summary
#description: |
  #Stellarium renders 3D photo-realistic skies in real-time. With Stellarium, you
  #really see what you can see with your eyes, binoculars or a small telescope.
adopt-info: stellarium
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

architectures: #build Architectures
   - build-on: amd64 
   #- build-on: i386
   #- build-on: arm64
   #- build-on: armhf

apps:
  stellarium:
    #command: desktop-launch $SNAP/usr/bin/stellarium
    command: bin/desktop-launch $SNAP/usr/bin/stellarium
    #desktop: share/applications/stellarium.desktop
    common-id: org.stellarium.Stellarium
    plugs: [desktop, wayland, x11, unity7, gsettings, opengl, network, network-bind, audio-playback, home, raw-usb]
    #shared interfaces
    environment:
      HOME: "$SNAP_USER_COMMON"
      #DISABLE_WAYLAND: 1
      #__EGL_VENDOR_LIBRARY_DIRS: $SNAP/usr/share/glvnd/egl_vendor.d
      "QT_PLUGIN_PATH": $"QT_PLUGIN_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins/"
      "QTWEBENGINEPROCESS_PATH": $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/libexec

    plugs: 
      - home
      - network
      - pulseaudio
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl


 
 layout: 
    #/share/applications: #not working
      #symlink: $SNAP/usr/share
    #/usr/share/qt5:
        #bind: $SNAP/usr/share/qt5

parts:
  stellarium:
    plugin: cmake
    #configflags:
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
    source: https://github.com/Stellarium/stellarium.git
    source-type: git
    #source-depth : 1
    #source-tag: v0.20.1
    #organize:
      #snap/stellarium-daily/current/usr: usr
      #snap/stellarium-daily/current/share: share
    parse-info: [usr/share/metainfo/org.stellarium.Stellarium.appdata.xml] #appstream info
    after: [desktop-stellarium]
    #filesets: 
      #f_exclude:
        #- -usr/share/icons/hicolor/64x64/apps/*
    #prime:
      #- $f_exclude

    override-pull: |
      snapcraftctl pull
      set -x
      
      # From Obs-studio
      # Checkout that latest stable version
      last_committed_tag="$(git -C ../src tag | grep -v stellarium | sort -V | tail -n 1)"
      #last_committed_tag="$(git ls-remote --tags https://github.com/Stellarium/stellarium.git | grep -v {} | awk -F/ '{ print $3 }' | sort -V |tail -n 1)"
      last_released_tag="$(snap info stellarium-daily | awk '$1 == "latest/beta:" { print $2 }')"
      
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        #pwd
        git fetch
        cd ../src
        git checkout "${last_committed_tag}"
        #git clone -b "${last_committed_tag}" --depth 1 https://github.com/Stellarium/stellarium.git .
        #snapcraftctl set-version "${last_committed_tag}"
      #else
        #git clone --depth 1 https://github.com/Stellarium/stellarium.git .
        #snapcraftctl set-version "$(echo "$(git ls-remote --tags https://github.com/Stellarium/stellarium.git | grep -v {} | awk -F/ '{ print $3 }' | sort -V |tail -n 1)-g$(git ls-remote https://github.com/Stellarium/stellarium.git HEAD | awk '{ print substr($1,1,7)}')")"
        #snapcraftctl set-version "${last_committed_tag}-g$(git ls-remote https://github.com/Stellarium/stellarium.git HEAD | awk '{ print substr($1,1,7)}')"
      fi

      snapcraftctl set-version "$(git describe --tag)"

    override-build: |
      snapcraftctl build
      set -x
      #mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      #cp ../src/data/stellarium.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications
      #mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/16x16/apps
      #cp ../src/data/icons/16x16/stellarium.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/16x16/apps
      #mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/32x32/apps
      #cp ../src/data/icons/32x32/stellarium.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/32x32/apps
      #mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/48x48/apps
      #cp ../src/data/icons/48x48/stellarium.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/48x48/apps
      #mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/64x64/apps
      #cp ../src/data/icons/64x64/stellarium.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/64x64/apps
      #mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/128x128/apps
      #cp ../src/data/icons/128x128/stellarium.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/128x128/apps
      #mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps
      #cp ../src/data/icons/256x256/stellarium.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps
      #mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/512x512/apps
      #cp ../src/data/icons/512x512/stellarium.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/512x512/apps
      
    #override-prime: |
      #set -x
      #snapcraftctl prime
      #mkdir -p $SNAPCRAFT_PRIME/usr/share/icons/hicolor/64x64/apps
      #cp $SNAPCRAFT_PART_SRC/data/icons/64x64/stellarium.png $SNAPCRAFT_PRIME/usr/share/icons/hicolor/64x64/apps
      
    build-packages:
      - build-essential
      - doxygen
      - gettext
      - libqt5multimedia5-plugins
      - libqt5positioning5
      - libqt5positioning5-plugins
      - libqt5svg5-dev
      - libqt5opengl5-dev
      - libqt5serialport5-dev
      - qtwebengine5-dev
      - mesa-common-dev
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtdeclarative5-dev-tools
      - qtscript5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - qtmultimedia5-dev
      - qtpositioning5-dev
      - zlib1g-dev
    stage-packages:
      - libasyncns0
      - libflac8
      - gtk3-nocsd
      - libogg0
      - libqt5multimedia5
      - libqt5multimediawidgets5
      - libqt5opengl5
      - libqt5positioning5
      - libqt5printsupport5
      - libqt5script5
      - libqt5serialport5
      - libqt5webenginewidgets5
      - libqt5webenginecore5
      - libqt5webengine5
      - libsndfile1
      - libvorbis0a
      - libvorbisenc2
      - libpulse0
   
  # This part installs the qt5 dependencies and a `desktop-launch` script to initialise
  # desktop-specific features such as fonts, themes and the XDG environment.
  # 
  # It is copied straight from the snapcraft desktop helpers project. Please periodically
  # check the source for updates and copy the changes.
  #    https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  #  
  
  desktop-stellarium:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    source-depth : 1
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
    - build-essential
    - qtbase5-dev
    - dpkg-dev
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libqt5gui5
    - libgdk-pixbuf2.0-0
    - libqt5svg5 # for loading icon themes which are svg
    - try: [appmenu-qt5] # not available on core18
    - locales-all
    - xdg-user-dirs
    - fcitx-frontend-qt5
    - libgtk2.0-0
    
  qt5-gtk-platform:
    plugin: nil
    stage-packages:
      - qt5-gtk-platformtheme

plugs:
  # Support for common GTK themes
  # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
