name: stellarium-daily # you probably want to 'snapcraft register <name>'
base: core22
summary: Free, open source planetarium software
description: |
  Stellarium renders 3D photo-realistic skies in real-time. With Stellarium, you
  really see what you can see with your eyes, binoculars or a small telescope.
adopt-info: stellarium
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
architectures: #build Architectures
   - build-on: amd64 
   #- build-on: arm64
   
# this line enables LZO compression for the snap
compression: lzo

#links:
#website: https://stellarium.org
#issues: [https://github.com/t4saha/stellarium-snap/issues, https://github.com/Stellarium/stellarium/issues]
#contact: https://github.com/t4saha/stellarium-snap
#help: https://github.com/Stellarium/stellarium/releases/download/v0.22.2/stellarium_user_guide-0.22.2-1.pdf
#translation: https://www.transifex.com/stellarium/stellarium

apps:
  stellarium:
    command: bin/desktop-launch $SNAP/usr/bin/stellarium
    common-id: org.stellarium.Stellarium
    plugs: [desktop, desktop-legacy, browser-support, x11, unity7, gsettings, opengl, network, network-bind, audio-playback, home, raw-usb]
    #shared interfaces
    environment:
      HOME: "$SNAP_USER_COMMON"
      DISABLE_WAYLAND: 1 # wayland is broken
      QT_QPA_PLATFORMTHEME: xcb # gtk3 is very slow and buggy

layout:
  /usr/share/qt6:
    bind: $SNAP/usr/share/qt6
  /usr/share/X11:
    bind: $SNAP/usr/share/X11

parts:
  stellarium:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
    source: https://github.com/Stellarium/stellarium.git
    source-type: git
    parse-info: [usr/share/metainfo/org.stellarium.Stellarium.appdata.xml] #appstream info
    after: [ShowMySky, desktop-stellarium]
    override-pull: |
      # Checkout that latest stable version
      last_committed_tag="$(git ls-remote --tags https://github.com/Stellarium/stellarium.git | grep -v {} | awk -F/ '{ print $3 }' | sort -V |tail -n 1)"
      last_released_tag="$(snap info stellarium-daily | awk '$1 == "latest/beta:" { print $2 }')"
      
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git clone -b "${last_committed_tag}" --depth 1 https://github.com/Stellarium/stellarium.git $CRAFT_PART_SRC
      else
        craftctl default
      fi
      # Point icon to the correct location
      sed -i.bak -e 's|Icon=stellarium|Icon=/usr/share/icons/hicolor/64x64/apps/stellarium.png|g' data/org.stellarium.Stellarium.desktop
      craftctl set version=$(git describe --tags) 
    override-build: |
      if [ "$(arch)" = "aarch64" ]; then
        cmake $CRAFT_PART_SRC -DENABLE_SHOWMYSKY=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$CRAFT_PART_INSTALL/usr
        make
        make install
      else
        craftctl default
      fi
      find / ! -readable -prune -o -type f -name "libQt6WebEngineCore.so.*" -exec ls {} \; -exec execstack --clear-execstack {} \; || true
    build-packages:
      #Essential Build Dependencies
      - build-essential
      - zlib1g-dev
      - libgl1-mesa-dev
      - libdrm-dev
      #Optional Build Dependencies
      - gettext
      - doxygen
      - graphviz
      - libgps-dev
      #ShowMySky Build Dependencies
      - libglm-dev
      - libeigen3-dev
      #XKB Build Dependencies
      - libxkbcommon-x11-dev
      #QT6 Build Dependencies
      - qt6-base-dev
      - qt6-base-private-dev
      - qt6-multimedia-dev
      - qt6-positioning-dev
      - qt6-tools-dev
      - qt6-tools-dev-tools
      - qt6-base-dev-tools
      - qt6-qpa-plugins
      - qt6-image-formats-plugins
      - qt6-l10n-tools
      - qt6-webengine-dev
      - qt6-webengine-dev-tools
      - libqt6charts6-dev
      - libqt6opengl6-dev
      - libqt6positioning6-plugins
      - libqt6serialport6-dev
      # for execstack flag removal
      - execstack
      #Obsolete Dependencies
      #- libqt6svg6-dev
      #- mesa-common-dev
      #- qt6-declarative-dev
      #- qt6-declarative-dev-tools
      #- libxcb-xkb-dev
      #- libxkbcommon-dev      
      #- linguist-qt6
      #- libqt6webchannel6-dev
      #- libqt6webenginewidgets6
      #- libqt6webengine6-data
      #- libqt6webenginecore6-bin
    stage-packages:
      #Media Runtime Dependencies
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-libav
      - gstreamer1.0-vaapi
      #QT6 Runtime Dependencies
      - libqt6multimedia6
      - libqt6multimediawidgets6
      - libqt6opengl6
      - libqt6openglwidgets6
      - libqt6positioning6
      - libqt6printsupport6
      - libqt6serialport6
      - libqt6charts6
      - libqt6core6
      - libqt6dbus6
      - libqt6network6
      - libqt6gui6
      - libqt6qml6
      - libqt6qmlmodels6
      - libqt6quick6
      - libqt6quickwidgets6
      - libqt6webchannel6
      - libqt6webenginecore6-bin
      - libqt6webenginecore6
      - libqt6webengine6-data
      - libqt6webenginewidgets6
      - libqt6widgets6
      - qt6-gtk-platformtheme
      #- qt6-wayland #not working
      #GPS Funcionality
      - libgps28
      #OpenGL Runtime Dependencies
      - libglu1-mesa
      - freeglut3
      #Obsolete Runtime Dependencies
      #- libasyncns0
      #- libflac8
      #- gtk3-nocsd
      #- libogg0
      #- libsndfile1
      #- libvorbis0a
      #- libvorbisenc2
      #- libpulse0

  ShowMySky:  
    plugin: nil
    after: [desktop-stellarium]
    override-pull: |
      #craftctl default
      if [ "$(arch)" = "x86_64" ]; then
        git clone --depth 1 https://github.com/10110111/CalcMySky.git
      fi
    override-build: |
      #craftctl default
      if [ "$(arch)" = "x86_64" ]; then
        cd CalcMySky
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=$CRAFT_PART_INSTALL/usr .. -DQT_VERSION=6 
        make
        make install
      fi
    build-packages:
      - git
      - on amd64:
        - build-essential
        - libeigen3-dev
        - libglm-dev
        - libqt6opengl6-dev
        - libxkbcommon-x11-dev
  
  desktop-stellarium:
    source: https://github.com/t4saha/snapcraft-desktop-helpers-Qt6.git
    source-subdir: qt
    source-depth : 1
    plugin: make
    make-parameters: ["FLAVOR=qt6"]
    build-packages:
      - build-essential
      - qt6-base-dev
      - dpkg-dev
      - software-properties-common
    stage-packages:
      #Kebourd I/O
      - libxkbcommon0
      - xkb-data
      #Theming
      - fonts-ubuntu
      - dmz-cursor-theme
      - adwaita-icon-theme
      - qt6-gtk-platformtheme
      - libqt6svg6 # for loading icon themes which are svg
      - libgtk2.0-0
      - shared-mime-info
      - libgdk-pixbuf2.0-0
      #User Configaration
      - locales-all
      - xdg-user-dirs
      #QT6
      - qt6-qpa-plugins
      - qt6-wayland
      - libqt6gui6
      #Other
      - libgtk-3-common
      - libglib2.0-bin
      - libglib2.0-0
      - libglib2.0-data
      - gsettings-desktop-schemas
      #- fcitx-frontend-qt6
